# DÉPENDANCES:
#   - Utilise: Aucun (fichier de constantes)
#   - Importe: Aucun
#   - Utilisé par: orchestrator.py, __init__.py

"""
ShelfReader - EasyOCR Configuration
Constantes et paramètres de configuration pour EasyOCR.
"""

# Paramètres de prétraitement
CLAHE_CLIP_LIMIT = 3.0
CLAHE_TILE_GRID_SIZE = (6, 6)
BILATERAL_D = 9
BILATERAL_SIGMA_COLOR = 75
BILATERAL_SIGMA_SPACE = 75
GAUSSIAN_SIGMA = 1.0
ADAPTIVE_BLOCK_SIZE = 7
ADAPTIVE_C = 3

# Paramètres OCR EasyOCR
OCR_WIDTH_THS = 0.3
OCR_HEIGHT_THS = 0.3
OCR_CONTRAST_THS = 0.05
OCR_ADJUST_CONTRAST = 0.7
OCR_TEXT_THRESHOLD = 0.5
OCR_LINK_THRESHOLD = 0.3

# Paramètres de détection de tranches
DOWNSAMPLE_FACTOR = 3
GAUSSIAN_BLUR_SIGMA = 3
BINARIZE_CUTOFF_FACTOR = 100.0
VERTICAL_ERODE_LENGTH = 50
VERTICAL_ERODE_ITERATIONS = 1
VERTICAL_DILATE_LENGTH = 10
VERTICAL_DILATE_ITERATIONS = 1
SHORT_CLUSTER_THRESHOLD_FRACTION = 0.30

# Paramètres de regroupement
MIN_SPINE_LINES_THRESHOLD = 5
HORIZONTAL_GROUP_THRESHOLD_BASE = 50
ADAPTIVE_THRESHOLD_MIN = 10
ADAPTIVE_THRESHOLD_MAX = 35
FONT_SIZE_RATIO_STRICT = 1.5
FONT_SIZE_RATIO_TOLERANT = 0.7
FONT_SIZE_STRICT_MULTIPLIER = 0.75
FONT_SIZE_TOLERANT_MULTIPLIER = 1.25

# Paramètres ICCC 2013
CANNY_MIN = 50
CANNY_MAX = 150
ICCC_PIXEL_THRESHOLD_RATIO = 0.5
ICCC_DILATE_WIDTH = 1
ICCC_DILATE_HEIGHT = 3
ICCC_MIN_HEIGHT_RATIO = 0.05